kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-postgres-data
  namespace: gitlab
  annotations:
    volume.beta.kubernetes.io/storage-class: "gitlab"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
